version: '3.8'

services:

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.20.0
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://root:password@db:5432/todoapp
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecretkey
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "cf9VzyOtA46RftsVox0dvILrZkJev61b"}'
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    depends_on:
      - db
    restart: always

  auth:
    build:
      context: ./auth
    ports:
      - "3001:3001"
    environment:
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_ADMIN_SECRET: adminsecretkey
      JWT_SECRET: cf9VzyOtA46RftsVox0dvILrZkJev61b
      PORT: 3001
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - hasura
    restart: always

volumes:
  db_data:
